services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--import-realm", "--http-port", "7080", "--https-port", "7443"]
    volumes:
    - ./mcp-realm.json:/opt/keycloak/data/import/mcp-realm.json
    ports:
    - "7080:7080"
    - "7443:7443"