binds:
- listeners:
  - routes:
## ==========================================================
## Remote server: Backend and MCP Authentication
## ==========================================================
    - backends:
      - mcp:
          targets:
          - mcp:
              host: localhost
              path: /mcp
              port: 3002
            name: echo
      matches:
      - path:
          exact: /echo/mcp
      - path:
          exact: /.well-known/oauth-protected-resource/echo/mcp
      policies:
        # backendTLS: {}
        cors:
          allowHeaders:
          - mcp-protocol-version
          - content-type
          allowOrigins:
          - '*'
        mcpAuthentication:
          mode: optional
          issuer: http://localhost:3001
          jwksUrl: http://localhost:3001/.well-known/jwks.json
          audience: http://localhost:3000/echo/mcp
          resourceMetadata:
            resource: http://localhost:3000/echo/mcp
            scopesSupported:
            - offline_access
            bearerMethodsSupported:
            - header
            - body
            - query
            resourceDocumentation: http://localhost:3000/echo/docs
            resourcePolicyUri: http://localhost:3000/echo/policies

    - backends:
      - mcp:
          targets:
          - mcp:
              host: localhost
              path: /mcp
              port: 3003
            name: printenv
      matches:
      - path:
          exact: /printenv/mcp
      - path:
          exact: /.well-known/oauth-protected-resource/printenv/mcp
      policies:
        backendTLS: {}
        cors:
          allowHeaders:
          - mcp-protocol-version
          - content-type
          allowOrigins:
          - '*'
        mcpAuthentication:
          mode: optional
          issuer: http://localhost:3001
          jwksUrl: http://localhost:3001/.well-known/jwks.json
          audience: http://localhost:3000/printenv/mcp
          resourceMetadata:
            resource: http://localhost:3000/printenv/mcp
            scopesSupported:
            - offline_access
            bearerMethodsSupported:
            - header
            - body
            - query
            resourceDocumentation: http://localhost:3000/printenv/docs
            resourcePolicyUri: http://localhost:3000/printenv/policies

  port: 3000

